### ISSUE TITLE
Organise !nextweek and !thisweek by module

### ISSUE THREAD

**Issue by CammyFentreux** [CammyFentreux/Discord-Canvas-Bot#20]
Currently multiple assignments for the same module can be on opposite ends of the message

**Comment by CammyFentreux** [comment]
Not sure how we could implement this, since it would mean losing the current sort-by-date method which is useful in it's own right. Now they have optional arguments to search by module this may not be necessary

**Comment by Douile** [comment]
Ye think the search by module provides this functionality as would prefer to keep chronological
